hms_app/urls.py
from .views import PasswordsChangeView
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name = 'hms_app'

urlpatterns = [
    path('list_of_appointments/', views.appointments, name='appointments'),
    path('list_of_departments/', views.departments, name='departments'),
    path('add_department/', views.add_department, name='add_department'),
    path('edit_department/<int:department_id>', views.edit_department, name='edit_department'),
    path('list_of_doctors/', views.doctors, name='doctors'),
    path('edit_doctor/<int:doctor_id>', views.edit_doctor, name="edit_doctor"),
    path('list_of_patients/', views.patients, name='patients'),
    path('patient_register/', views.patient_register, name='patient_register'),
    path('doctor_apply/', views.doctor_apply, name='doctor_apply'),
    path('patient_login/', views.patient_login, name='patient_login'),
    path('doctor_login/', views.doctor_login, name='doctor_login'),
    path('patient_appointment/', views.make_appointment, name='patient_appointment'),
    path('patient_profile/', views.patient_profile, name='patient_profile'),
    path('doctor_profile/', views.doctor_profile, name='doctor_profile'),
    path('patient_edit_profile/<int:user_id>', views.patient_edit_profile, name="patient_edit_profile"),
    path('doctor_edit_profile/<int:user_id>', views.doctor_edit_profile, name="doctor_edit_profile"),
    path('patient_edit_appointment/<int:appointment_id>', views.patient_edit_appointment, name='patient_edit_appointment'),
    path('doctor_edit_appointment/<int:appointment_id>', views.doctor_edit_appointment, name='doctor_edit_appointment'),
    path('view_doctor_profile/<int:doctor_id>', views.view_doctor_profile, name='view_doctor_profile'),
    path('view_patient_profile/<int:patient_id>', views.view_patient_profile, name='view_patient_profile'),
    path('password/', PasswordsChangeView.as_view(), name='change_password'),
    path('password_changed/', views.password_changed, name='password_changed'),
    path('appointment_deleted/<int:appointment_id>', views.delete_appointment, name='delete_appointment'),
    path('department_deleted/<int:department_id>', views.delete_department, name='delete_department'),
    path('patient_deleted/<int:patient_id>', views.delete_patient, name='delete_patient'),
    path('doctor_deleted/<int:doctor_id>', views.delete_doctor, name='delete_doctor'),
    path('head_removed/<int:department_id>', views.remove_head, name='remove_head'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hospital_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from hms_app import views

urlpatterns = [
    path('admin_sign_up/', views.admin_sign_up, name='admin_sign_up'),
    path('admin_login/', views.admin_login, name='admin_login'),
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('hms_app/', include('hms_app.urls')),
    path('logout/', views.logout, name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hms_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.views.generic.edit import UpdateView
from . import models
from django.contrib.auth.forms import UserChangeForm

class AdminUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']
        widgets = {'password':forms.PasswordInput()}

class DoctorUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password']
        widgets = {'password':forms.PasswordInput()}

class EditDoctorUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email',]

class DoctorForm(forms.ModelForm):
    department_id = forms.ModelChoiceField(queryset=models.Department.objects.all(), empty_label="Choose your Department", to_field_name="id", label="Department")
    class Meta:
        model = models.Doctor
        fields = ['sex', 'profile_pic']

class EditDoctorForm(forms.ModelForm):
    department_id = forms.ModelChoiceField(queryset=models.Department.objects.all(), empty_label="Choose your Department", to_field_name="id", label="Department")
    class Meta:
        model = models.Doctor
        fields = ['sex', 'profile_pic',]

class AdminEditDoctorForm(forms.ModelForm):
    department_id = forms.ModelChoiceField(queryset=models.Department.objects.all(), empty_label="Choose your Department", to_field_name="id", label="Department")
    class Meta:
        model = models.Doctor
        fields = ['status',]

class PatientUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password']
        widgets = {'password':forms.PasswordInput()}

class EditPatientUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email',]

class PatientForm(forms.ModelForm):
    # chosen_doctor_id = forms.ModelChoiceField(queryset=models.Doctor.objects.all().filter(status=True), empty_label="Name and Department", to_field_name="user_id")
    class Meta:
        model = models.Patient
        fields = ['sex', 'profile_pic']

class EditPatientForm(forms.ModelForm):
    # chosen_doctor_id = forms.ModelChoiceField(queryset=models.Doctor.objects.all().filter(status=True), empty_label="Name and Department", to_field_name="user_id")
    class Meta:
        model = models.Patient
        fields = ['sex', 'profile_pic']

class ChangePatientProfilePic(forms.ModelForm):
        class Meta:
            model = models.Patient
            fields = ['profile_pic',]

class PatientAppointmentForm(forms.ModelForm):
    doctor_id = forms.ModelChoiceField(queryset=models.Doctor.objects.all().filter(status=True), empty_label="Choose your Doctor", to_field_name="user_id", label="Doctor")
    class Meta:
        model = models.Appointment
        fields = ['appointment_date', 'appointment_time', 'appointment_reason',]

class PatientEditAppointmentForm(forms.ModelForm):
    doctor_id = forms.ModelChoiceField(queryset=models.Doctor.objects.all().filter(status=True), empty_label="Choose your Doctor", to_field_name="user_id", label="Doctor")
    class Meta:
        model = models.Appointment
        fields = ['appointment_date', 'appointment_time', 'appointment_reason',]

class DoctorEditAppointmentForm(forms.ModelForm):
    class Meta:
        model = models.Appointment
        fields = ['appointment_status', 'appointment_comments',]

class DepartmentForm(forms.ModelForm):
    doctor_id = forms.ModelChoiceField(queryset=models.Doctor.objects.all().filter(status=True), empty_label="Choose your Doctor", to_field_name="user_id", label="Doctor", required=False)
    class Meta:
        model = models.Department
        fields = ['department_name',]

class EditDepartmentForm(forms.ModelForm):
    doctor_id = forms.ModelChoiceField(queryset=models.Doctor.objects.all().filter(status=True), empty_label="Choose your Doctor", to_field_name="user_id", label="Doctor", required=False)
    class Meta:
        model = models.Department
        fields = ['department_name',]

hms_app/views.py
from django.shortcuts import render, reverse
from django.urls import reverse_lazy 
from django.contrib.auth import authenticate, login, logout as django_logout
from . import forms, models
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import PasswordChangeView

is_patient = False
is_doctor = False
doctor_status = False

class PasswordsChangeView(PasswordChangeView):
    form_class = PasswordChangeForm
    template_name='hms_app/change_password.html'
    success_url = reverse_lazy('hms_app:password_changed')

    def get_context_data(self, **kwargs):
        global is_patient
        global is_doctor
        global doctor_status
        context = super().get_context_data(**kwargs)
        context['is_patient'] = is_patient
        context['is_doctor'] = is_doctor
        context['doctor_status'] = doctor_status
        return context

@login_required
def password_changed(request):
    global is_patient
    global is_doctor
    global doctor_status
    context = {'is_patient':is_patient, 'is_doctor':is_doctor, 'doctor_status':doctor_status}
    return render(request, 'hms_app/change_password_success.html', context)

def index(request):
    global is_patient
    global is_doctor
    global doctor_status
    if is_patient:
        patient = models.Patient.objects.get(user_id=request.user.id)
        doctor_list = models.Doctor.objects.all().filter(status=True)
        appointment_list = models.Appointment.objects.all().filter(patient_id=patient.id)
        return render(request, 'hms_app/index.html', {'is_patient':is_patient, 'is_doctor':is_doctor, 'appointment_list': appointment_list, 'doctor_list': doctor_list})
    elif is_doctor:
        doctor = models.Doctor.objects.get(user_id=request.user.id)
        patient_list = models.Patient.objects.all()
        appointment_list = models.Appointment.objects.all().filter(doctor_id=doctor.id)
        return render(request, 'hms_app/index.html', {'is_patient':is_patient, 'is_doctor':is_doctor, 'appointment_list': appointment_list, 'doctor_status': doctor_status, 'patient_list': patient_list})
    else:
        return render(request, 'hms_app/index.html', {'is_patient':is_patient, 'is_doctor':is_doctor})

@login_required
def departments(request):
    department_list = models.Department.objects.all()
    doctor_list = models.Doctor.objects.all().filter(status=True)
    return render(request, 'hms_app/list_of_departments.html', {'department_list':department_list, 'doctor_list': doctor_list})

@login_required
def doctors(request):
    doctor_list = models.Doctor.objects.all()
    department_list = models.Department.objects.all()
    return render(request, 'hms_app/list_of_doctors.html', {'doctor_list':doctor_list, 'department_list':department_list})

@login_required
def patients(request):
    patient_list = models.Patient.objects.all()
    return render(request, 'hms_app/list_of_patients.html', {'patient_list':patient_list,})

@login_required
def appointments(request):
    appointment_list = models.Appointment.objects.all()
    patient_list = models.Patient.objects.all()
    doctor_list = models.Doctor.objects.all()
    department_list = models.Department.objects.all()
    return render(request, 'hms_app/list_of_appointments.html', {'appointment_list':appointment_list, 'patient_list':patient_list, 'doctor_list':doctor_list, 'department_list':department_list})

@login_required
def edit_doctor(request, doctor_id):
    edited = False
    doctor = models.Doctor.objects.get(id=doctor_id)
    doctor_form = forms.AdminEditDoctorForm(instance=doctor)
    if request.method=='POST':
        doctor_form = forms.AdminEditDoctorForm(instance=doctor, data=request.POST)
        if doctor_form.is_valid():
            doctor = doctor_form.save(commit=False)
            department = models.Department.objects.get(id=request.POST.get('department_id'))
            doctor.department_id = department.id
            doctor = doctor.save()
            edited = True
        else:
            print(doctor_form.errors)
    else:
        doctor_form = forms.AdminEditDoctorForm(instance=doctor)
    return render(request, 'hms_app/edit_doctor.html', {'doctor_form':doctor_form, 'doctor':doctor, 'edited':edited})

@login_required
def edit_department(request, department_id):
    edited = False
    department = models.Department.objects.get(id=department_id)
    department_form = forms.EditDepartmentForm(instance=department)
    if request.method=='POST':
        department_form = forms.EditDepartmentForm(instance=department, data=request.POST)
        if department_form.is_valid():
            department = department_form.save(commit=False)
            try:
                doctor = models.Doctor.objects.get(user_id=request.POST.get('doctor_id'))
                if doctor is None:
                    department.doctor_id = None
                else:
                    department.doctor_id = doctor.id
            except:
                pass
            department = department.save()
            edited = True
        else:
            print(department_form.errors)
    else:
        department_form = forms.EditDepartmentForm(instance=department)
    return render(request, 'hms_app/edit_department.html', {'department_form':department_form, 'department':department, 'edited':edited})

@login_required
def add_department(request):
    added = False
    dept_form = forms.DepartmentForm()
    if request.method == 'POST':
        dept_form = forms.DepartmentForm(request.POST)
        if dept_form.is_valid():
            department = dept_form.save()
            try:
                doctor = models.Doctor.objects.get(user_id=request.POST.get('doctor_id'))
                department.doctor_id = doctor.id
                department.save()
            except:
                department.save()
            added = True
        else:
            print(dept_form.errors)
    else:
        dept_form = forms.DepartmentForm()
    return render(request, 'hms_app/add_department.html', {'dept_form':dept_form, 'added':added})

@login_required
def logout(request):
    global is_patient 
    global is_doctor
    is_patient = False
    is_doctor = False
    django_logout(request)
    return HttpResponseRedirect(reverse('index'))

def admin_sign_up(request):
    signed_up = False
    user_form = forms.AdminUserForm()
    if request.method == 'POST':
        user_form = forms.AdminUserForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            signed_up = True
        else:
            print(user_form.errors)
    else:
        user_form = forms.AdminUserForm()
    return render(request, 'hms_app/admin_sign_up.html', {'user_form':user_form, 'signed_up':signed_up})

def admin_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_superuser:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Your account is not active.')
        else:
            print("Someone tried to login and failed.")
            print("Username: {} and Password: {}".format(username, password))
            return HttpResponse("Invalid login details. Please try again.")
    else:
        return render(request, 'hms_app/admin_login.html', {})

def doctor_apply(request):
    applied = False
    user_form = forms.DoctorUserForm()
    doctor_form = forms.DoctorForm()
    if request.method=='POST':
        user_form = forms.DoctorUserForm(request.POST)
        doctor_form = forms.DoctorForm(request.POST, request.FILES)
        if user_form.is_valid and doctor_form.is_valid:
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            doctor = doctor_form.save(commit=False)
            department = models.Department.objects.get(id=request.POST.get('department_id'))
            doctor.department_id = department.id
            doctor.user = user
            doctor = doctor.save()
            applied = True
        else:
            print(user_form.errors, doctor_form.errors)
    else:
        user_form = forms.DoctorUserForm()
        doctor_form = forms.DoctorForm()
    return render(request, 'hms_app/doctor_application.html', {'user_form':user_form, 'doctor_form':doctor_form, 'applied':applied})

def patient_register(request):
    registered = False
    user_form = forms.PatientUserForm()
    patient_form = forms.PatientForm()
    if request.method=='POST':
        user_form = forms.PatientUserForm(request.POST)
        patient_form = forms.PatientForm(request.POST, request.FILES)
        if user_form.is_valid and patient_form.is_valid:
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            patient = patient_form.save(commit=False)
            patient.user = user 
            patient = patient.save()
            registered = True
        else:
            print(user_form.errors, patient_form.errors)
    else:
        user_form = forms.PatientUserForm()
        patient_form = forms.PatientForm()
    return render(request, 'hms_app/patient_registration.html', {'user_form':user_form, 'patient_form':patient_form, 'registered':registered})

def patient_login(request):
    global is_patient
    if request.method == 'POST':
        patient_username = request.POST.get('patient_username')
        patient_password = request.POST.get('patient_password')
        patient = authenticate(username=patient_username, password=patient_password)
        if patient:
            if patient.is_active:

templates/hms_app/admin_login.html
{% extends 'hms_app/base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1 class="display-4">Admin Login</h1>
    <p class="lead">Fill out the necessary fields to login.</p>
    <hr class="my-4">
    <form action="{% url 'admin_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">
        <label for="password">Password:</label>
        <input type="password" name="password">
        <input type="submit" value="Log In">
    </form>
</div>

{% endblock %}

templates/hms_app/change_password_success.html
{% extends 'hms_app/base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1 class="display-4">Password successfully changed!</h1>
</div>

{% endblock %}

templates/hms_app/doctor_application.html
{% extends 'hms_app/base.html' %}
{% load static %}

{% block body_block %}
<div class="jumbotron">
    {% if applied %}
    <h1>Thank you for applying!</h1>
    {% else %}
    <h1 class="display-4">Registration for Doctors</h1>
    <p class="lead">Fill out the necessary fields to apply.</p>
    <hr class="my-4">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ doctor_form.as_p }}
        <input type="submit" value="Apply">
    </form>
    {% endif %}
</div>
{% endblock %}

templates/hms_app/doctor_edit_profile.html
{% extends 'hms_app/base.html' %}
{% load static %}

{% block body_block %}
<div class="jumbotron">
    {% if edited %}
    <h1>You've successfully edited your profile!</h1>
    {% else %}
    <h1 class="display-4">Edit Profile</h1>
    <hr class="my-4">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        <a class="btn btn-outline-primary btn-sm" href="{% url 'hms_app:change_password' %}" role="button">Change Password</a>
        <p></p>
        {{ doctor_form.as_p }}
        <input type="submit" value="Update Profile">
    </form>
    {% endif %}
</div>
{% endblock %}

templates/hms_app/doctor_login.html
{% extends 'hms_app/base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1 class="display-4">Doctor Login</h1>
    <p class="lead">Fill out the necessary fields to login.</p>
    <hr class="my-4">
    <form action="{% url 'hms_app:doctor_login' %}" method="post">
        {% csrf_token %}
        <label for="doctor_username">Username:</label>
        <input type="text" name="doctor_username" placeholder="Enter Username">
        <label for="doctor_password">Password:</label>
        <input type="password" name="doctor_password">
        <input type="submit" value="Log In">
    </form>
</div>

{% endblock %}

templates/hms_app/edit_department.html
{% extends 'hms_app/base.html' %}
{% load static %}

{% block body_block %}
<div class="jumbotron">
    {% if edited %}
    <h1>You've successfully edited the department's details!</h1>
    {% elif deleted %}
    <h1>You've deleted a department.</h1>
    {% elif removed %}
    <h1>You've removed the head.</h1>
    {% else %}
    <h1 class="display-4">Edit Department</h1>
    <p class="lead">{{ department.department_name }}</p>
    <form method="post">
        {% csrf_token %}
        {{ department_form.as_p }}
        <input type="submit" value="Edit">
    </form>
    <p></p>
    <a class="btn btn-outline-danger btn-sm" href="{% url 'hms_app:remove_head' department.id %}" role="button">Remove Head</a>
    <p></p>
    <a class="btn btn-outline-danger btn-sm" href="{% url 'hms_app:delete_department' department.id %}"
        role="button">Delete Department</a>
    {% endif %}
</div>
{% endblock %}

templates/hms_app/edit_doctor.html
{% extends 'hms_app/base.html' %}
{% load static %}

{% block body_block %}
<div class="jumbotron">
    {% if edited %}
    <h1>You've successfully edited the doctor's profile!</h1>
    {% elif deleted %}
    <h1>You've deleted the doctor.</h1>
    {% else %}
    <h1 class="display-4">Edit Doctor</h1>
    <p class="lead">Dr. {{ doctor.user.first_name }} {{ doctor.user.last_name }}</p>
    <form method="post">
        {% csrf_token %}
        {{ doctor_form.as_p }}
        <input type="submit" value="Edit">
        <p></p>
        <a class="btn btn-outline-danger btn-sm" href="{% url 'hms_app:delete_doctor' doctor.id %}" role="button">Delete Doctor</a>
        <p></p>
    </form>
    {% endif %}
</div>
{% endblock %}

templates/hms_app/list_of_appointments.html
{% extends "hms_app/base.html" %}
{% block body_block %}

<div class="jumbotron jumbotron-fluid">
    <div class="container">
        {% if appointment_list %}
        <h1 class="display-4">List of Appointments</h1>
        <table class="table table-striped table-bordered">
            <thead>
                <th>Patient Name</th>
                <th>Appointment Date</th>
                <th>Appointment Time</th>
                <th>Doctor Name</th>
                <th>Department</th>
                <th>Status</th>
            </thead>
            {% for app in appointment_list %}
            <tr>
                <td>{% for pat in patient_list %}
                    {% if pat.id == app.patient_id %}
                    <a href="{% url 'hms_app:view_patient_profile' pat.id %}">{{ pat.user.last_name }}, {{ pat.user.first_name }}</a>
                    {% endif %}
                    {% endfor %}
                </td>
                <td>{{ app.appointment_date }}</td>
                <td>{{ app.appointment_time }}</td>
                <td>{% for doc in doctor_list %}
                    {% if doc.id == app.doctor_id %}
                    <a href="{% url 'hms_app:view_doctor_profile' doc.id %}">Dr. {{ doc.user.first_name }} {{ doc.user.last_name }}</a></td>
                    {% endif %}
                    {% endfor %}
                <td>{% for doc in doctor_list %}
                    {% for dept in department_list %}
                    {% if doc.id == app.doctor_id %}
                    {% if doc.department_id == dept.id %}
                    {{ dept.department_name }}
                    {% endif %}
                    {% endif %}
                    {% endfor %}
                    {% endfor %}
                </td>
                <td>{% if app.appointment_status %}
                    Approved
                    {% else %}
                    Pending
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
        {% else %}
        <h1 class="display-4">There are no Appointments made</h1>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/hms_app/list_of_departments.html
{% extends "hms_app/base.html" %}
{% block body_block %}

<div class="jumbotron jumbotron-fluid">
    <div class="container">
    {% if department_list %}
    <h1 class="display-4">List of Departments</h1>
    <a class="btn btn-outline-primary btn-lg" href="{% url 'hms_app:add_department' %}" role="button">Add Department</a>
    <table class="table table-striped table-bordered">
        <thead>
            <th>Department Name</th>
            <th>Department Head</th>
        </thead>
        {% for dept in department_list %}
        <tr>
            <td><a class="btn btn-outline-primary btn-sm" href="{% url 'hms_app:edit_department' dept.id %}" role="button">Edit</a> {{ dept.department_name }}</td>
            <td>{% for doc in doctor_list %}
                {% if doc.id == dept.doctor_id %}
                <a href="{% url 'hms_app:view_doctor_profile' doc.id %}">Dr. {{ doc.user.first_name }} {{ doc.user.last_name }}</a>
                {% endif %}
                {% endfor %}
            </td>
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <h1 class="display-4">There are no departments</h1>
    <a class="btn btn-outline-primary btn-lg" href="{% url 'hms_app:add_department' %}" role="button">Add Department</a>
    {% endif %}
</div>
</div>
{% endblock %}

templates/hms_app/list_of_doctors.html
{% extends "hms_app/base.html" %}
{% block body_block %}

<div class="jumbotron jumbotron-fluid">
    <div class="container">
        {% if doctor_list %}
        <h1 class="display-4">List of Doctors</h1>
        <table class="table table-striped table-bordered">
            <thead>
                <th>Doctor Name</th>
                <th>Department</th>
                <th>Status</th>
            </thead>
            {% for doc in doctor_list %}
            <tr>
                <td><a class="btn btn-outline-primary btn-sm" href="{% url 'hms_app:edit_doctor' doc.id %}" role="button">Edit</a> <a href="{% url 'hms_app:view_doctor_profile' doc.id %}">Dr. {{ doc.user.first_name }} {{ doc.user.last_name }}</a></td>
                <td>{% for dept in department_list %}
                    {% if doc.department_id == dept.id %}
                    {{ dept.department_name }}
                    {% endif %}
                    {% endfor %}
                </td>
                <td>{% if doc.status %}
                    Active
                    {% else %}
                    Inactive
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
        {% else %}
        <h1 class="display-4">There are no doctors</h1>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/hms_app/patient_appointment.html
{% extends 'hms_app/base.html' %}
{% load static %}

{% block body_block %}
<div class="jumbotron">
    {% if appointed %}
    <h1>Thank you for making your appointment!</h1>
    <p class="lead">Please wait for the approval of your appointment.</p>
    {% else %}
    <h1 class="display-4">Appointment Form</h1>
    <p class="lead">Fill out the necessary fields to appoint.</p>
    <hr class="my-4">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ appointment_form.as_p }}
        <input type="submit" value="Appoint">
    </form>
    {% endif %}
</div>
{% endblock %}

templates/hms_app/patient_edit_profile.html
{% extends 'hms_app/base.html' %}
{% load static %}

{% block body_block %}
<div class="jumbotron">
    {% if edited %}
    <h1>You've successfully edited your profile!</h1>
    {% else %}
    <h1 class="display-4">Edit Profile</h1>
    <hr class="my-4">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        <a class="btn btn-outline-primary btn-sm" href="{% url 'hms_app:change_password' %}" role="button">Change Password</a>
        <p></p>
        {{ patient_form.as_p }}
        <input type="submit" value="Update Profile">
    </form>
    {% endif %}
</div>
{% endblock %}

templates/hms_app/patient_profile.html
{% extends 'hms_app/base.html' %}
{% load static %}

{% block body_block %}
<div class="jumbotron">
    <img src="{{ user.patient.profile_pic.url }}" alt="{{ request.user.username }}'s Profile pic" width="200">
    <a class="btn btn-outline-primary btn-lg" href="{% url 'hms_app:patient_edit_profile' user.id %}" role="button">Edit Profile</a>
    <p>Username: {{ request.user.username }}</p>
    <p>First name: {{ request.user.first_name }}</p>
    <p>Last name: {{ request.user.last_name }}</p>
    <p>E-mail: {{ request.user.email }}</p>
    <p>Sex: {{ request.user.patient.sex }}</p>
</div>
{% endblock %}

templates/hms_app/view_patient_profile.html
{% extends 'hms_app/base.html' %}
{% load static %}

{% block body_block %}
<div class="jumbotron">
    <img src="{{ patient.profile_pic.url }}" alt="{{ patient.user.username }}'s Profile pic" width="200">
    <p>First name: {{ patient.user.first_name }}</p>
    <p>Last name: {{ patient.user.last_name }}</p>
    <p>E-mail: {{ patient.user.email }}</p>
    <p>Sex: {{ patient.sex }}</p>
</div>
{% endblock %}